name: NodeJS Te

on:
  push:
    branches: ["InentorySystem-Backend-mongoDb-nodeJs"]
  pull_request:
    branches: ["InentorySystem-Backend-mongoDb-nodeJs"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 19.6.0
        uses: actions/setup-node@v3
        with:
          node-version: 19.6.0
      - run: npm i
      - run: npm run build --if-present
      - run: npm test
